name: ci

on: [push, workflow_dispatch]

env:
  NODE_OPTIONS: --max-old-space-size=3200
  CC_TEST_REPORTER_ID: 8263f3329c9a25abc9ad21473a65deabd4c8f0cd54db6e7fbba1a85fb6e5b829

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v3, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v3, with: { node-version: 18, cache: 'yarn' } }
      - run: yarn --frozen-lockfile --prefer-offline
      - run: yarn build
      - name: test
        run: |
          curl -s -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          yarn test
          ./cc-test-reporter after-build -t lcov

  release-job:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    permissions:
      contents: write
      id-token: write
    steps:
      - { uses: actions/checkout@v3, with: { persist-credentials: true } }
      - { uses: actions/setup-node@v3, with: { node-version: 18, cache: 'yarn' } }

      # Cache for npm/npx in ~/.npm
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-v1-${{ runner.os }}

      - run: yarn --frozen-lockfile --prefer-offline
      - run: yarn build-prod

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx @naturalcycles/semantic-release
